<?php

use Illuminate\Database\Seeder;

class StatesProvinciaCubaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      	$states = array(
				array('name' => "Pinar del Rio",'id_country' => 55),
				array('name' => "Artemisa",'id_country' => 55),
				array('name' => "La Habana",'id_country' => 55),
				array('name' => "Mayabeque",'id_country' => 55),
				array('name' => "Matanzas",'id_country' => 55),
				array('name' => "Villa Clara",'id_country' => 55),
				array('name' => "Cienfuegos",'id_country' => 55),
				array('name' => "Sancti Spiritus",'id_country' => 55),
				array('name' => "Ciego de Avila",'id_country' => 55),
				array('name' => "Camaguey",'id_country' => 55),
				array('name' => "Las Tunas",'id_country' => 55),
				array('name' => "Holguin",'id_country' => 55),
				array('name' => "Granma",'id_country' => 55),
				array('name' => "Santiago de Cuba",'id_country' => 55),
				array('name' => "Guantánamo",'id_country' => 55),
				array('name' => "Isla de la Juventud",'id_country' => 55),
			);

 $municipios = array(	
       	array('name' => 'Sandino', 'province' => 'Pinar del Rio', 'cubapack_code' => '010100'),
		array('name' =>  'Mantua', 'province' => 'Pinar del Rio', 'cubapack_code' => '010200'),
		array('name' => 'Minas de Matahambre', 'province' => 'Pinar del Rio', 'cubapack_code' => '010300'),
		array('name' => 'Viñales', 'province' => 'Pinar del Rio', 'cubapack_code' => '010400'),
		array('name' => 'La Palma', 'province' => 'Pinar del Rio', 'cubapack_code' => '010500'),
		array('name' => 'Candelaria', 'province' => 'Pinar del Rio', 'cubapack_code' => '010700'),
		array('name' => 'San Cristobal', 'province' => 'Pinar del Rio', 'cubapack_code' => '010800'),
		array('name' => 'Los Palacios', 'province' => 'Pinar del Rio', 'cubapack_code' => '010900'),
		array('name' => 'Consolacion del Sur', 'province' => 'Pinar del Rio', 'cubapack_code' => '011000'),
		array('name' => 'Pinar del Rio', 'province' => 'Pinar del Rio', 'cubapack_code' => '011100'),
		array('name' => 'San Luis', 'province' => 'Pinar del Rio', 'cubapack_code' => '011200'),
		array('name' => 'San Juan y Martinez', 'province' => 'Pinar del Rio', 'cubapack_code' => '011300'),
		array('name' => 'Guane', 'province' => 'Pinar del Rio', 'cubapack_code' => '011400'),
		array('name' => 'Mariel', 'province' => 'Artemisa', 'cubapack_code' => '020100'),
		array('name' => 'Guanajay', 'province' => 'Artemisa', 'cubapack_code' => '020200'),
		array('name' => 'Caimito', 'province' => 'Artemisa', 'cubapack_code' => '020300'),
		array('name' => 'Bauta', 'province' => 'Artemisa', 'cubapack_code' => '020400'),
		array('name' => 'San Antonio de los Banos', 'province' => 'Artemisa', 'cubapack_code' => '020500'),
		array('name' => 'Guira de Melena', 'province' => 'Artemisa', 'cubapack_code' => '021700'),
		array('name' => 'Alquizar', 'province' => 'Artemisa', 'cubapack_code' => '021800'),
		array('name' => 'Artemisa', 'province' => 'Artemisa', 'cubapack_code' => '021900'),
		array('name' => 'Bahia Honda', 'province' => 'Artemisa', 'cubapack_code' => '022000'),
		array('name' => 'San Cristobal', 'province' => 'Artemisa', 'cubapack_code' => '022100'),
		array('name' => 'Candelaria', 'province' => 'Artemisa', 'cubapack_code' => '022200'),
		array('name' => 'Playa', 'province' => 'La Habana', 'cubapack_code' => '030100'),
		array('name' => 'Plaza de la Revolución', 'province' => 'La Habana', 'cubapack_code' => '030200'),
		array('name' => 'Centro Habana', 'province' => 'La Habana', 'cubapack_code' => '030300'),
		array('name' => 'La Habana Vieja', 'province' => 'La Habana', 'cubapack_code' => '030400'),
		array('name' => 'Regla', 'province' => 'La Habana', 'cubapack_code' => '030500'),
		array('name' => 'La Habana del Este', 'province' => 'La Habana', 'cubapack_code' => '030600'),
		array('name' => 'Guanabacoa', 'province' => 'La Habana', 'cubapack_code' => '030700'),
		array('name' => 'San Miguel del Padrón', 'province' => 'La Habana', 'cubapack_code' => '030800'),
		array('name' => 'Diez de Octubre', 'province' => 'La Habana', 'cubapack_code' => '030900'),
		array('name' => 'Cerro', 'province' => 'La Habana', 'cubapack_code' => '031000'),
		array('name' => 'Marianao', 'province' => 'La Habana', 'cubapack_code' => '031100'),
		array('name' => 'La Lisa', 'province' => 'La Habana', 'cubapack_code' => '031200'),
		array('name' => 'Boyeros', 'province' => 'La Habana', 'cubapack_code' => '031300'),
		array('name' => 'Arroyo Naranjo', 'province' => 'La Habana', 'cubapack_code' => '031400'),
		array('name' => 'Cotorro', 'province' => 'La Habana', 'cubapack_code' => '031500'),
		array('name' => 'Matanzas', 'province' => 'Matanzas', 'cubapack_code' => '040100'),
		array('name' => 'Cárdenas', 'province' => 'Matanzas', 'cubapack_code' => '040200'),
		array('name' => 'Varadero', 'province' => 'Matanzas', 'cubapack_code' => '040300'),
		array('name' => 'Martí', 'province' => 'Matanzas', 'cubapack_code' => '040400'),
		array('name' => 'Colon', 'province' => 'Matanzas', 'cubapack_code' => '040500'),
		array('name' => 'Perico', 'province' => 'Matanzas', 'cubapack_code' => '040600'),
		array('name' => 'Jovellanos', 'province' => 'Matanzas', 'cubapack_code' => '040700'),
		array('name' => 'Pedro Betancourt', 'province' => 'Matanzas', 'cubapack_code' => '040800'),
		array('name' => 'Limonar', 'province' => 'Matanzas', 'cubapack_code' => '040900'),
		array('name' => 'Union de Reyes', 'province' => 'Matanzas', 'cubapack_code' => '041000'),
		array('name' => 'Cienaga de Zapata', 'province' => 'Matanzas', 'cubapack_code' => '041100'),
		array('name' => 'Jaguey Grande', 'province' => 'Matanzas', 'cubapack_code' => '041200'),
		array('name' => 'Calimete', 'province' => 'Matanzas', 'cubapack_code' => '041300'),
		array('name' => 'Los Arabos', 'province' => 'Matanzas', 'cubapack_code' => '041400'),
		array('name' => 'Corralillo', 'province' => 'Villa Clara', 'cubapack_code' => '050100'),
		array('name' => 'Quemado de Guines', 'province' => 'Villa Clara', 'cubapack_code' => '050200'),
		array('name' => 'Sagua la Grande', 'province' => 'Villa Clara', 'cubapack_code' => '050300'),
		array('name' => 'Encrucijada', 'province' => 'Villa Clara', 'cubapack_code' => '050400'),
		array('name' => 'Camajuani', 'province' => 'Villa Clara', 'cubapack_code' => '050500'),
		array('name' => 'Caibarien', 'province' => 'Villa Clara', 'cubapack_code' => '050600'),
		array('name' => 'Remedios', 'province' => 'Villa Clara', 'cubapack_code' => '050700'),
		array('name' => 'Placetas', 'province' => 'Villa Clara', 'cubapack_code' => '050800'),
		array('name' => 'Santa Clara', 'province' => 'Villa Clara', 'cubapack_code' => '050900'),
		array('name' => 'Cifuentes', 'province' => 'Villa Clara', 'cubapack_code' => '051000'),
		array('name' => 'Santo Domingo', 'province' => 'Villa Clara', 'cubapack_code' => '051100'),
		array('name' => 'Ranchuelo', 'province' => 'Villa Clara', 'cubapack_code' => '051200'),
		array('name' => 'Manicaragua', 'province' => 'Villa Clara', 'cubapack_code' => '051300'),
		array('name' => 'Aguada de Pasajeros', 'province' => 'Cienfuegos', 'cubapack_code' => '060100'),
		array('name' => 'Rodas', 'province' => 'Cienfuegos', 'cubapack_code' => '060200'),
		array('name' => 'Palmira', 'province' => 'Cienfuegos', 'cubapack_code' => '060300'),
		array('name' => 'Lajas', 'province' => 'Cienfuegos', 'cubapack_code' => '060400'),
		array('name' => 'Cruces', 'province' => 'Cienfuegos', 'cubapack_code' => '060500'),
		array('name' => 'Cumanayagua', 'province' => 'Cienfuegos', 'cubapack_code' => '060600'),
		array('name' => 'Cienfuegos', 'province' => 'Cienfuegos', 'cubapack_code' => '060700'),
		array('name' => 'Abreus', 'province' => 'Cienfuegos', 'cubapack_code' => '060800'),
		array('name' => 'Yaguajay', 'province' => 'Sancti Spiritus', 'cubapack_code' => '070100'),
		array('name' => 'Jatibonico', 'province' => 'Sancti Spiritus', 'cubapack_code' => '070200'),
		array('name' => 'Taguasco', 'province' => 'Sancti Spiritus', 'cubapack_code' => '070300'),
		array('name' => 'Cabaiguan', 'province' => 'Sancti Spiritus', 'cubapack_code' => '070400'),
		array('name' => 'Fomento', 'province' => 'Sancti Spiritus', 'cubapack_code' => '070500'),
		array('name' => 'Trinidad', 'province' => 'Sancti Spiritus', 'cubapack_code' => '070600'),
		array('name' => 'Sancti Spiritus', 'province' => 'Sancti Spiritus', 'cubapack_code' => '070700'),
		array('name' => 'La Sierpe', 'province' => 'Sancti Spiritus', 'cubapack_code' => '070800'),
		array('name' => 'Chambas', 'province' => 'Ciego de Avila', 'cubapack_code' => '080100'),
		array('name' => 'Moron', 'province' => 'Ciego de Avila', 'cubapack_code' => '080200'),
		array('name' => 'Bolivia', 'province' => 'Ciego de Avila', 'cubapack_code' => '080300'),
		array('name' => 'Primero de Enero', 'province' => 'Ciego de Avila', 'cubapack_code' => '080400'),
		array('name' => 'Ciro Redondo', 'province' => 'Ciego de Avila', 'cubapack_code' => '080500'),
		array('name' => 'Florencia', 'province' => 'Ciego de Avila', 'cubapack_code' => '080600'),
		array('name' => 'Majagua', 'province' => 'Ciego de Avila', 'cubapack_code' => '080700'),
		array('name' => 'Ciego de Avila', 'province' => 'Ciego de Avila', 'cubapack_code' => '080800'),
		array('name' => 'Venezuela', 'province' => 'Ciego de Avila', 'cubapack_code' => '080900'),
		array('name' => 'Baragua', 'province' => 'Ciego de Avila', 'cubapack_code' => '081000'),
		array('name' => 'Esmeralda', 'province' => 'Camaguey', 'cubapack_code' => '090200'),
		array('name' => 'Sierra de Cubitas', 'province' => 'Camaguey', 'cubapack_code' => '090300'),
		array('name' => 'Minas', 'province' => 'Camaguey', 'cubapack_code' => '090400'),
		array('name' => 'Nuevitas', 'province' => 'Camaguey', 'cubapack_code' => '090500'),
		array('name' => 'Guaimaro', 'province' => 'Camaguey', 'cubapack_code' => '090600'),
		array('name' => 'Sibanicu', 'province' => 'Camaguey', 'cubapack_code' => '090700'),
		array('name' => 'Camaguey', 'province' => 'Camaguey', 'cubapack_code' => '090800'),
		array('name' => 'Florida', 'province' => 'Camaguey', 'cubapack_code' => '090900'),
		array('name' => 'Vertientes', 'province' => 'Camaguey', 'cubapack_code' => '091000'),
		array('name' => 'Jimaguayu', 'province' => 'Camaguey', 'cubapack_code' => '091100'),
		array('name' => 'Najasa', 'province' => 'Camaguey', 'cubapack_code' => '091200'),
		array('name' => 'Santa Cruz del Sur', 'province' => 'Camaguey', 'cubapack_code' => '091300'),
		array('name' => 'Manati', 'province' => 'Las Tunas', 'cubapack_code' => '100100'),
		array('name' => 'Jesus Menendez', 'province' => 'Las Tunas', 'cubapack_code' => '100300'),
		array('name' => 'Majibacoa', 'province' => 'Las Tunas', 'cubapack_code' => '100400'),
		array('name' => 'Las Tunas', 'province' => 'Las Tunas', 'cubapack_code' => '100500'),
		array('name' => 'Jobabo', 'province' => 'Las Tunas', 'cubapack_code' => '100600'),
		array('name' => 'Colombia', 'province' => 'Las Tunas', 'cubapack_code' => '100700'),
		array('name' => 'Amancio', 'province' => 'Las Tunas', 'cubapack_code' => '100800'),
		array('name' => 'Holguin', 'province' => 'Holguin', 'cubapack_code' => '110100'),
		array('name' => 'Gibara', 'province' => 'Holguin', 'cubapack_code' => '110200'),
		array('name' => 'Banes', 'province' => 'Holguin', 'cubapack_code' => '110400'),
		array('name' => 'Antilla', 'province' => 'Holguin', 'cubapack_code' => '110500'),
		array('name' => 'Baguanos', 'province' => 'Holguin', 'cubapack_code' => '110600'),
		array('name' => 'Calixto Garcia', 'province' => 'Holguin', 'cubapack_code' => '110700'),
		array('name' => 'Cacocum', 'province' => 'Holguin', 'cubapack_code' => '110800'),
		array('name' => 'Urbano Noris', 'province' => 'Holguin', 'cubapack_code' => '110900'),
		array('name' => 'Cueto', 'province' => 'Holguin', 'cubapack_code' => '111000'),
		array('name' => 'Mayari', 'province' => 'Holguin', 'cubapack_code' => '111100'),
		array('name' => 'Frank Pais', 'province' => 'Holguin', 'cubapack_code' => '111200'),
		array('name' => 'Sagua de Tanamo', 'province' => 'Holguin', 'cubapack_code' => '111300'),
		array('name' =>  'Moa', 'province' => 'Holguin', 'cubapack_code' => '111400'),
		array('name' =>  'Rio Cauto', 'province' => 'Granma', 'cubapack_code' => '120100'),
		array('name' => 'Cauto Cristo', 'province' => 'Granma', 'cubapack_code' => '120200'),
		array('name' => 'Jiguani', 'province' => 'Granma', 'cubapack_code' => '120300'),
		array('name' => 'Yara', 'province' => 'Granma', 'cubapack_code' => '120500'),
		array('name' => 'Manzanillo', 'province' => 'Granma', 'cubapack_code' => '120600'),
		array('name' => 'Campechuela', 'province' => 'Granma', 'cubapack_code' => '120700'),
		array('name' => 'Niquero', 'province' => 'Granma', 'cubapack_code' => '120900'),
		array('name' => 'Media Luna', 'province' => 'Granma', 'cubapack_code' => '120800'),
		array('name' => 'Pilon', 'province' => 'Granma', 'cubapack_code' => '121000'),
		array('name' => 'Bartolome Maso', 'province' => 'Granma', 'cubapack_code' => '121100'),
		array('name' => 'Buey Arriba', 'province' => 'Granma', 'cubapack_code' => '121200'),
		array('name' => 'Guisa', 'province' => 'Granma', 'cubapack_code' => '121300'),
		array('name' => 'Contramaestre', 'province' => 'Santiago de Cuba', 'cubapack_code' => '130100'),
		array('name' => 'Mella', 'province' => 'Santiago de Cuba', 'cubapack_code' => '130200'),
		array('name' => 'San Luis', 'province' => 'Santiago de Cuba', 'cubapack_code' => '130300'),
		array('name' => 'Segundo Frente', 'province' => 'Santiago de Cuba', 'cubapack_code' => '130400'),
		array('name' => 'Santiago de Cuba', 'province' => 'Santiago de Cuba', 'cubapack_code' => '130600'),
		array('name' => 'Palma Soriano', 'province' => 'Santiago de Cuba', 'cubapack_code' => '130700'),
		array('name' => 'Tercer Frente', 'province' => 'Santiago de Cuba', 'cubapack_code' => '130800'),
		array('name' => 'Guama', 'province' => 'Santiago de Cuba', 'cubapack_code' => '130900'),
		array('name' => 'El Salvador', 'province' => 'Guantánamo', 'cubapack_code' => '140100'),
		array('name' =>  'Guantanamo', 'province' => 'Guantánamo', 'cubapack_code' => '140200'),
		array('name' => 'Yateras', 'province' => 'Guantánamo', 'cubapack_code' => '140300'),
		array('name' => 'Baracoa', 'province' => 'Guantánamo', 'cubapack_code' => '140400'),
		array('name' => 'Maisi', 'province' => 'Guantánamo', 'cubapack_code' => '140500'),
		array('name' => 'Imias', 'province' => 'Guantánamo', 'cubapack_code' => '140600'),
		array('name' => 'San Antonio del Sur', 'province' => 'Guantánamo', 'cubapack_code' => '140700'),
		array('name' => 'Manuel Tames', 'province' => 'Guantánamo', 'cubapack_code' => '140800'),
		array('name' => 'Caimanera', 'province' => 'Guantánamo', 'cubapack_code' => '140900'),
		array('name' => 'Niceto Perez', 'province' => 'Guantánamo', 'cubapack_code' => '141000'),
		array('name' => 'Gerona', 'province' => 'Isla de la Juventud', 'cubapack_code' => '150100'),
		array('name' => 'La Fe', 'province' => 'Isla de la Juventud', 'cubapack_code' => '150200'),
		array('name' => 'Bejucal', 'province' => 'Mayabeque', 'cubapack_code' => '160100'),
		array('name' => 'Quivican', 'province' => 'Mayabeque', 'cubapack_code' => '160200'),
		array('name' => 'Batabano', 'province' => 'Mayabeque', 'cubapack_code' => '160300'),
		array('name' => 'San Jose de las Lajas', 'province' => 'Mayabeque', 'cubapack_code' => '160400'),
		array('name' => 'Melena del Sur', 'province' => 'Mayabeque', 'cubapack_code' => '160500'),
		array('name' => 'Guines', 'province' => 'Mayabeque', 'cubapack_code' => '160600'),
		array('name' => 'San Nicolas', 'province' => 'Mayabeque', 'cubapack_code' => '160700'),
		array('name' => 'Nueva Paz', 'province' => 'Mayabeque', 'cubapack_code' => '160800'),
		array('name' => 'Madruga', 'province' => 'Mayabeque', 'cubapack_code' => '160900'),
		array('name' => 'Jaruco', 'province' => 'Mayabeque', 'cubapack_code' => '161000'),
		array('name' => 'Santa Cruz del Norte', 'province' => 'Mayabeque', 'cubapack_code' => '161100'),
		array('name' => 'Bayamo', 'province' => 'Granma', 'cubapack_code' => '120400')
		);

	
		
			foreach($states as $value){
				$id_state = DB::table('imp_state')->insertGetId([
					'name' => $value['name'],
					'id_country' => $value['id_country']
				]);
				foreach ($municipios as $key) {
					if($value['name'] == $key['province']){
						DB::table('imp_city')->insert([
									'name' => $key['name'],
									'cubapack_code' => $key['cubapack_code'],
									'id_state' => $id_state
						]);
					}
				}
			}
    }
}
